SIPG_FORMAT_RULES = {
    "title_l1": {
        "label": "一级标题",
        "font": "宋体",
        "size_pt": 16,
        "bold": True,
        "space_before_pt": 10,
        "space_after_pt": 10,
        "line_spacing": 1.5,
    },
    "title_l2": {
        "label": "二级标题",
        "font": "宋体",
        "size_pt": 14,
        "bold": True,
        "space_before_pt": 10,
        "space_after_pt": 10,
        "line_spacing": 1.5,
    },
    "title_l3": {
        "label": "三级/四级标题",
        "font": "宋体",
        "size_pt": 10.5,
        "bold": True,
        "space_before_pt": 10,
        "space_after_pt": 10,
        "line_spacing": 1.5,
    },
    "body": {
        "label": "正文",
        "font": "宋体",
        "size_pt": 10.5,
        "bold": False,
        "space_before_pt": 0,
        "space_after_pt": 0,
        "line_spacing": 1.5,
        "first_line_indent_pt": 21,
        "alignment": "JUSTIFY",
    },
    "toc": {
        "label": "目录",
        "font": "宋体",
        "size_pt": 10.5,
        "bold": False,
        "space_before_pt": 0,
        "space_after_pt": 0,
        "line_spacing": 1.5,
    },
}
